### ISSUE TITLE
libobs download on cmake build fails with 403 status code

### ISSUE THREAD

**Issue by KevinBarbier2** [streamlabs/obs-studio-node#1008]
[ 25%] Performing download step (download, verify and extract) for 'libobs-download'
-- Downloading...
   dst='/mnt/dev/node/tests/obs/node_modules/@streamlabs/obs-studio-node/build/libobs-download/libobs-download-prefix/src/libobs--release-27.2.3.7z'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://obsstudios3.streamlabs.com/libobs--release-27.2.3.7z'
CMake Error at libobs-download/libobs-download-prefix/src/libobs-download-stamp/download-libobs-download.cmake:170 (message):
  Each download failed!

    error: downloading 'https://obsstudios3.streamlabs.com/libobs--release-27.2.3.7z' failed
          status_code: 22
          status_string: "HTTP response code said error"
          log:
          --- LOG BEGIN ---
            Trying 104.16.144.22:443...

  Connected to obsstudios3.streamlabs.com (104.16.144.22) port 443 (#0)

...

  The requested URL returned error: 403

[cmakejs.log](https://github.com/stream-labs/obs-studio-node/files/7235467/cmakejs.log)
[CMakeOutput.log](https://github.com/stream-labs/obs-studio-node/files/7235468/CMakeOutput.log)

**Comment by MilkerLiu** [comment]
missing LIBOBS_PLATFORM, e.g windows64 or osx

full url: https://obsstudios3.streamlabs.com/libobs-osx-release-27.2.3.7z

check file obs-studio-node/obs-studio-server/CMakeLists.txt
