### ISSUE TITLE
How to change the output file?

### ISSUE THREAD

**Issue by aza547** [streamlabs/obs-studio-node#1143]
As title.

Recording a monitor/window/game and I want to specify the output file (and location). Any advice? 

Thanks

**Comment by aza547** [comment]
Looks like this sets the path:
`setSetting('Output', 'RecFilePath', "C:/some/path");`

Also would like to know how to change the name of the file.

**Comment by aza547** [comment]
```
function setSetting(category, parameter, value) {
  let oldValue;

  // Getting settings container
  const settings = osn.NodeObs.OBS_settings_getSettings(category).data;
  console.log(settings);

  settings.forEach(subCategory => {
    subCategory.parameters.forEach(param => {
      if (param.name === parameter) {
        oldValue = param.currentValue;
        param.currentValue = value;
      }
    });
  });

  // Saving updated settings container
  if (value != oldValue) {
    osn.NodeObs.OBS_settings_saveSettings(category, settings);
  }
}
```

**Comment by aza547** [comment]
Looks like I need `FilenameFormatting` to be set, but can't find how to set this.

**Comment by summeroff** [comment]
You can find usage examples in tests
https://github.com/stream-labs/obs-studio-node/blob/4159b7b41ec52f3d7d2d3ebef1ee17ffdf5bca23/tests/osn-tests/src/test_nodeobs_settings.ts#L2339
