### ISSUE TITLE
OSX/Linux Support

### ISSUE THREAD

**Issue by msanterre** [streamlabs/obs-studio-node#115]
I'd love to use this library, but I need linux/osx support. 

Are there plans for this to happen?

If it's not on the roadmap at the moment, could I get a rough estimate of how much work would entail? I'd love to help.

**Comment by computerquip-streamlabs** [comment]
Hello. This library is in a bit of a rough spot at the moment. In particular, it's tied in bad ways to the streamlabs-obs client right now. Until that ends and we get proper abstractions, it'll likely stay platform specific. 

That said, the platform specific bits are the following:
* The windowing code in nodeobs_display.cpp
* node-libuiohook (which doesn't use libuiohook at all)
* Most of what's in the IPC code where any networking is concerned
* Probably random areas that shouldn't be platform specific at all

I'd love to work on this at some point but I'm still a ways away from getting the chance to. I can't give a rough estimate really but probably not this year if I'm honest.
