### ISSUE TITLE
The sceneitem alignment return type is wrong

### ISSUE THREAD

**Issue by n3g2** [streamlabs/obs-studio-node#1222]
https://github.com/stream-labs/obs-studio-node/blob/e0c671983b5ce4bcf1c273934d3320ca103ea97b/obs-studio-client/source/sceneitem.cpp#L535

I don't think the return here is Boolean. You can take a look [here](https://obsproject.com/docs/reference-scenes.html#c.obs_sceneitem_get_alignment).

**Comment by summeroff** [comment]
Thanks for your report. 
Issue will be fixed by.  https://github.com/stream-labs/obs-studio-node/pull/1256
