### ISSUE TITLE
audio often sounds robotic

### ISSUE THREAD

**Issue by Squimbert** [streamlabs/obs-studio-node#1323]
is this a bitrate issue? i'm not sure what's causing it. recording at 60fps in 1440p.

**Comment by aza547** [comment]
Did you solve this? Looking at a similar issue (I think you also reported in WR?) https://github.com/aza547/wow-recorder/issues/426

Looks like we can't use an audio encoder (and hence set the bitrate) for the AdvancedRecordingFactory but can for the SimpleRecordingFactory. 

Wondering if all that is required is to set it on the track.

**Comment by Squimbert** [comment]
I never solved it. Still often robotic sounding.
