### ISSUE TITLE
mac(x86_64) compilation failed, "https://obsstudios3.streamlabs.com/libobs-osx-release-29.1.3sl6-x86_64.7z" non-existent

### ISSUE THREAD

**Issue by ou-bing** [streamlabs/obs-studio-node#1392]
I am exec `cmake ..  -DCMAKE_PREFIX_PATH=%CD%/libobs-src/cmake/ -DCMAKE_BUILD_TYPE="Debug"` in the `build` directory

**Comment by ou-bing** [comment]
Perhaps there is no access permission?
![image](https://github.com/stream-labs/obs-studio-node/assets/32380374/036062b1-0e1a-417f-87df-593c4ee67136)

**Comment by summeroff** [comment]
We have an issue with building recent version of libobs for macOS. So right now osn only can be build for windows too. 

There is a latest version before this changes https://github.com/stream-labs/obs-studio-node/releases/tag/0.23.107

**Comment by ou-bing** [comment]
> We have an issue with building recent version of libobs for macOS. So right now osn only can be build for windows too.
> 
> There is a latest version before this changes https://github.com/stream-labs/obs-studio-node/releases/tag/0.23.107

thx, I have successfully compiled this version😄
