### ISSUE TITLE
About " node-window-rendering" in macOS

### ISSUE THREAD

**Issue by Tanoshi0625** [streamlabs/obs-studio-node#1394]
Now i successfully compiled osn for arm64 version, but i have a question about "node-window-rendering". 
this is my error message:
<img width="1232" alt="image" src="https://github.com/stream-labs/obs-studio-node/assets/90015990/fabd95cf-8557-4077-9e2c-f0156e589efe">
node-window-rendering not support arm64, what version do you use? please help me!

**Comment by summeroff** [comment]
right now we use this version [1.0.19](https://github.com/stream-labs/node-window-rendering/releases/tag/1.0.19). 
arm64 support from 1.0.18.
