### ISSUE TITLE
Why the need for IPC?

### ISSUE THREAD

**Issue by alirazeen** [streamlabs/obs-studio-node#195]
Hello,

I am just curious. Why is there a need for IPC between the obs-studio-server and obs-studio-client? Why couldn't they both run in the same address space?

Thanks in advance for your time!

**Comment by EddyGharbi** [comment]
Hello,

Sorry for the late response. There were 2 main reasons for us to split obs-studio-node into obs-studio-client and obs-studio-server.
 1. Do not block as much the main nodejs event loop and directly make calls from the renderer to obs. This makes us gain in terms of app responsiveness.
 2. If a crash happens outside of obs-studio (-> obs-studio-client / electron), it doesn't crash the whole application. We can keep the stream on and ask the user when they want to restart the app.

Hope that helps / makes sense.

**Comment by alirazeen** [comment]
I believe you can load a native node module, start a new worker thread, and then make all calls to OBS from that new thread. That shouldn't block the main event loop and in theory, should make the app more responsive. That said, your crash isolation requirement is a good reason for IPC.

Thanks for this!
