### ISSUE TITLE
SubCategory paramsCount type mismatch

### ISSUE THREAD

**Issue by hhgyu** [streamlabs/obs-studio-node#427]
Type does not match in serialization and deserialization.
https://github.com/stream-labs/obs-studio-node/blob/c12f28f7b5b02e345bc8a09c0957dd136f4d38fc/obs-studio-client/source/nodeobs_settings.hpp#L124

https://github.com/stream-labs/obs-studio-node/blob/c12f28f7b5b02e345bc8a09c0957dd136f4d38fc/obs-studio-server/source/nodeobs_settings.h#L135

uint32_t != size_t

### Visual Studio 2015 32bit

stdint.h
```
typedef unsigned int       uint32_t;
```

vcruntime.h
```
typedef unsigned int     size_t;
```

### Visual Studio 2015 64bit

stdint.h
```
typedef unsigned int       uint32_t;
```

vcruntime.h
```
typedef unsigned __int64 size_t; == typedef unsigned long long size_t;
```

**Comment by hhgyu** [comment]
#428

**Comment by RodrigoHolztrattner** [comment]
Thanks for your find, I'm addressing/fixing the issue and checking for any other type mismatch.
