### ISSUE TITLE
RecType add subType

### ISSUE THREAD

**Issue by hhgyu** [streamlabs/obs-studio-node#429]
https://github.com/stream-labs/obs-studio-node/blob/810da04c696e29c087b73568cca027b9138e4b09/obs-studio-server/source/nodeobs_settings.cpp#L2178-L2184
```
	recType.subType		= "OBS_COMBO_FORMAT_STRING";
```

**Comment by RodrigoHolztrattner** [comment]
Also fixed, thanks for finding it!
