### ISSUE TITLE
RecFileNameWithoutSpace sizeOfCurrentValue error

### ISSUE THREAD

**Issue by hhgyu** [streamlabs/obs-studio-node#430]
https://github.com/stream-labs/obs-studio-node/blob/c12f28f7b5b02e345bc8a09c0957dd136f4d38fc/obs-studio-server/source/nodeobs_settings.cpp#L1879-L1887

```
recFileNameWithoutSpace.sizeOfCurrentValue = sizeof(noSpace);
```

As a result of a reference to another source, it is correct to use it as sizeof.

https://github.com/stream-labs/obs-studio-node/blob/c12f28f7b5b02e345bc8a09c0957dd136f4d38fc/obs-studio-server/source/nodeobs_settings.cpp#L308-L313

**Comment by RodrigoHolztrattner** [comment]
Thanks for your catch!
