### ISSUE TITLE
Windows x32 & Mac support

### ISSUE THREAD

**Issue by lorux0** [streamlabs/obs-studio-node#512]
Hello, what is necessary to support windows x32 and mac builds and how can be done? Thanks

**Comment by EddyGharbi** [comment]
Hi, the main things are our IPC library, our display and our packing/deployment process. We are working on it and we are close to have a working solution to then begin internal testing.

**Comment by EddyGharbi** [comment]
Closing this issue, Mac support is now done and will be merged onto the base branch in the next few days.

**Comment by chengjingfeng** [comment]
thanks @EddyGharbi  when it will be available?
