### ISSUE TITLE
How to create a display

### ISSUE THREAD

**Issue by hrueger** [streamlabs/obs-studio-node#623]
Hi,
with the help of [this](https://github.com/Envek/obs-studio-node-example) repository, I was able to get the basic setup with electron working.
However, for now just adding scenes, sources and recording works. I'd like to add a output display.
In `streamlabs-obs` I found this code: [https://github.com/stream-labs/streamlabs-obs/blob/e707f9819a10296893f4d3e058d12110c1ec44a7/app/services/video.ts#L254-L275](https://github.com/stream-labs/streamlabs-obs/blob/e707f9819a10296893f4d3e058d12110c1ec44a7/app/services/video.ts#L254-L275)
So I have the following code:
```JavaScript
const osn = require("obs-studio-node");
 // do all the initialization stuff, like here: https://github.com/Envek/obs-studio-node-example/blob/a099849c5e053cced4cfb23f9a250f95e5c7967f/obsRecorder.js#L10-L64
const t = new BrowserWindow({
    height: 300,
    width: 400,
    webPreferences: {
      nodeIntegration: true,
    }
  });

  osn.NodeObs.OBS_content_createDisplay(
    t.getNativeWindowHandle(),
    "test",
    1,
  );
```
But it just gives me the normal `BrowserWindow`.
Rendering mode can be 0, 1 or 2 as defined [here](https://github.com/stream-labs/obs-studio-node/blob/d54a2828247fbbb4704fc44089bcfcd78966966c/js/module.ts#L328-L332) but it doesn't work with any of them.

What am I missing or doing wrong?

**Comment by hrueger** [comment]
Sorry for another ping, but it's a great library and it would be very helpful if someone could just post a simple example for creating a display.
As you can tell from #578 there are quite some people who are interested in knowing how to use the library.

**Comment by chengjingfeng** [comment]
@hrueger 
for your reference：

//import obs-studio-node
const osn = require("obs-studio-node");

//get camera input
const obsVideoInput = osn.InputFactory.create('dshow_input', 'video', {
  audio_device_id: 'does_not_exist',
  video_device_id: 'does_not_exist',

});

var devieid = '';
const iListProperty = obsVideoInput.properties.get('video_device_id');
const cameraItems = iListProperty.details.items;
if(cameraItems.length > 0){
  devieid = cameraItems[0].value;
  cameraItems[0].selected = true;
  console.debug('cameraItems[0].name: ' + cameraItems[0].name)

}

const obsCameraInput = osn.InputFactory.create('dshow_input', 'video', {
  video_device_id: devieid,
});
obsVideoInput.release();

let settings02 = obsCameraInput.settings;
  settings['width'] = 320;
  settings['height'] = 240;
  obsCameraInput.update(settings02);
  obsCameraInput.save();
  //end get camera input

//create a camera display window
var cameraWindow = new BrowserWindow({ width: 320, height: 240 });
  
  osn.NodeObs.OBS_content_createSourcePreviewDisplay(
    cameraWindow.getNativeWindowHandle(),
    devieid,
    'myDisplay',
  );


osn.NodeObs.OBS_content_setShouldDrawUI('myDisplay', false);
osn.NodeObs.OBS_content_resizeDisplay('myDisplay', 320, 240);

//add camera input scene into output
osn.Global.setOutputSource(1, scene02);


you will find a new camera input display window. good luck.

**Comment by hrueger** [comment]
Thank you!

**Comment by aza547** [comment]
I'm struggling with this also, was there a solution?

**Comment by hrueger** [comment]
See here: https://github.com/hrueger/obs-studio-node-docs/blob/main/docs/displays.md

**Comment by aza547** [comment]
Thanks! I've been referencing these docs a lot - thanks for creating them. The bit I was missing was the resize, seems that it never gets drawn on the window without the call to `osn.NodeObs.OBS_content_resizeDisplay().`

I'm now facing another two problems:

1. The display is always on-top of the window. I'd like to allow menus / tooltips to overlay it. Any idea if it's possible?
![image](https://user-images.githubusercontent.com/32389325/235343695-d9cf045c-828f-4230-a361-399130e86673.png)

2. The call to OBS_Content_destroyDisplay to hide the display seems to freeze up my program. I've hacked around it for now with this, but bit nervous about leaving it like that.

```
    // I'd love to make OBS_content_destroyDisplay work here but I've not managed
    // so far. This is a hack to "hide" it by moving it off screen.
    osn.NodeObs.OBS_content_moveDisplay(this.previewName, 50000, 50000);
```

**Comment by aza547** [comment]
Seems like 1 is answered here:
https://github.com/stream-labs/obs-studio-node/issues/1229
