### ISSUE TITLE
Using external OBS plugins

### ISSUE THREAD

**Issue by viral98** [streamlabs/obs-studio-node#652]
How should one go about using plugins like [this](https://obsproject.com/forum/resources/obs-virtualcam.949/) along with NodeOBS

**Comment by EddyGharbi** [comment]
We currently support few OBS plugins. Since we don't have a QT frontend, we have to manually remove any of these dependencies and then integrate each plugin. We have forked multiple of them.

NodeOBS tries to load plugins for the path it is given.
