### ISSUE TITLE
Unable to get the Volmeter callback working

### ISSUE THREAD

**Issue by berkon** [streamlabs/obs-studio-node#881]
Unable to get the Volmeter callback working. I know that it works in Streamlabs OBS, but the code is quite complex for reverse engineering it. What I found out (and what I think should work) is the code below. Does someone have an idea what I'm doing wrong?

```
    let dev = osn.InputFactory.create ( 'wasapi_input_capture', 'mydevice', {device_id: 'Mikrofon (Logitech Webcam C925e)' })
    let volmeter = osn.VolmeterFactory.create ( 1 )
    volmeter.attach ( dev )
    volmeter.addCallback ( (a,b,c) => {
         console.log (a,b,c)
    })

    // Don't know if the following lines are required, but just in case ...
    osn.Global.setOutputSource ( 0, dev )
    let scene = osn.SceneFactory.create ("Scene")
    scene.add ( dev )
```

**Comment by berkon** [comment]
@summeroff, I saw that you posted a pull-request regarding the Volmeters, so I guess you got the Volmeters running. I'd greatly appreciate if you could give me a hint what's wrong with my code above!

**Comment by berkon** [comment]
Oh man! This was a really hard (2-day) nut to crack! I found out that this line must be added to the code in order to make the code above work:

`osn.NodeObs.RegisterSourceCallback ( (objs) => {} )`

**Comment by Amyas** [comment]
think
